trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'tm-test-app'

steps:
- template: pentest.yml
  parameters:
    url: "https://$(webAppName).azurewebsites.net/"
    port: '443'
    aggressiveMode: true