schedules:
- cron: "0 0 * * *"
  displayName: 'Nightly Security Scan'
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'tm-test-app'

stages:
- stage: Security
  jobs:
  - job: RunOWASPZap
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: pentest-pwsh.yml
      parameters:
        url: "https://$(webAppName).azurewebsites.net/"
        port: '443'
        aggressive: true